// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ7F339pPukT8UWkYWOPve2lE_vWxnf3Y',
    appId: '1:54303802826:web:4bdd7baded8c36a5bf7b33',
    messagingSenderId: '54303802826',
    projectId: 'yourmanager-652a6',
    authDomain: 'yourmanager-652a6.firebaseapp.com',
    storageBucket: 'yourmanager-652a6.firebasestorage.app',
    measurementId: 'G-SN5RSQ52VY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxVQiTBO88l2429-OCPcLqZbKEqcgUnQ4',
    appId: '1:54303802826:android:4168da101912ec7dbf7b33',
    messagingSenderId: '54303802826',
    projectId: 'yourmanager-652a6',
    storageBucket: 'yourmanager-652a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD31NePoi0qh4h1dJs2PCDbtnG4DoDzVBo',
    appId: '1:54303802826:ios:5133198ae9e795ddbf7b33',
    messagingSenderId: '54303802826',
    projectId: 'yourmanager-652a6',
    storageBucket: 'yourmanager-652a6.firebasestorage.app',
    androidClientId: '54303802826-7fsctqjctrm23mm9oe34pum4p2ngeao2.apps.googleusercontent.com',
    iosClientId: '54303802826-hd9ub938rp4liinlqq71ism8raremk4o.apps.googleusercontent.com',
    iosBundleId: 'com.example.superManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD31NePoi0qh4h1dJs2PCDbtnG4DoDzVBo',
    appId: '1:54303802826:ios:5133198ae9e795ddbf7b33',
    messagingSenderId: '54303802826',
    projectId: 'yourmanager-652a6',
    storageBucket: 'yourmanager-652a6.firebasestorage.app',
    androidClientId: '54303802826-7fsctqjctrm23mm9oe34pum4p2ngeao2.apps.googleusercontent.com',
    iosClientId: '54303802826-hd9ub938rp4liinlqq71ism8raremk4o.apps.googleusercontent.com',
    iosBundleId: 'com.example.superManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJ7F339pPukT8UWkYWOPve2lE_vWxnf3Y',
    appId: '1:54303802826:web:e82911f5920aa2a4bf7b33',
    messagingSenderId: '54303802826',
    projectId: 'yourmanager-652a6',
    authDomain: 'yourmanager-652a6.firebaseapp.com',
    storageBucket: 'yourmanager-652a6.firebasestorage.app',
    measurementId: 'G-7PQ5FWFYQC',
  );
}
